twig:
    paths: ['%kernel.project_dir%/user/templates', '%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    default_path: '%kernel.project_dir%/user/templates'
    form_themes: [ 'bootstrap_4_horizontal_layout.html.twig' ]