services:
  php:
    image: dehare/unchained:latest
    volumes:
      - .env.local:/var/www/.env.local
      - build:/var/www/public/build
      - media:/var/www/public/media
     depends_on:
       - mariadb

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
    volumes:
      - default.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/var/www/media
      - build:/var/www/build

 mariadb:
   image: mariadb
   volumes:
     - mysql:/var/lib/mysql
   environment:
     MYSQL_USER: user
     MYSQL_PASSWORD: secret
     MYSQL_RANDOM_ROOT_PASSWORD: "yes"
     MYSQL_DATABASE: unchained
     MYSQL_PORT: 3306
   volumes:
     - mysql:/var/lib/mysql/

volumes:
  build:
  media:
  mysql:
